version: '2'

services:

    # recorder 
    recorder219:
       image: chrberger/cluon-amd64:latest
       restart: on-failure
       network_mode: "host"
       volumes: 
       - ./recordings219cluon:/opt/recordings
       #- /media/usb-test/recordings219cluon:/opt/recordings
       working_dir: "/opt/recordings"
       command: sh -c "cluon-OD4toStdout --cid=219 > `date +CID-219-recording-%Y-%m-%d_%H%M%S.rec`"  

    recorder48:
       image: chrberger/cluon-amd64:latest
       restart: on-failure
       network_mode: "host"
       volumes:
       - ./recordings48cluon:/opt/recordings
       #- /media/usb-test/recordings48cluon:/opt/recordings
       working_dir: "/opt/recordings"
       command: sh -c "cluon-OD4toStdout --cid=48 > `date +CID-48-recording-%Y-%m-%d_%H%M%S.rec`"

    #configure camera on the computer first
    proxy-camera:
       #image: proxy-camera:local
       #local image, change ENTRYPOINT to CMD in Dockerfile to enable change nice value from command line
       image: proxy-camera:0af4299
       network_mode: host
       group_add:
           - video
       ipc: host
       privileged: true
       user: root
       devices:
           - "/dev/video0:/dev/video0"
       environment:
           - DISPLAY=$DISPLAY
       #    - CLUON_SHAREDMEMORY_POSIX=1
       volumes:
           - /tmp/.X11-unix:/tmp/.X11-unix
           - "/dev/shm:/dev/shm"
       ulimits:
         memlock:
           soft: 5600000 #1516032
           hard: 5600000
       command: "nice -n -10 opendlv-device-camera-opencv --name=cam0 --bgr2rgb --cid=${CID} --camera=/dev/video0 --width=2560 --height=720 --bpp=24 --freq=15"

#    cfsd18-perception-detectcone:
#        image: chalmersfsd/cfsd18-perception-detectcone:pre-release-4f13908
#        network_mode: "host"
#        ipc: host
#        working_dir: /opt
#        environment:
#          - DISPLAY=$DISPLAY
#        volumes:
#         - /tmp/.X11-unix:/tmp/.X11-unix
#         #- /media/usb-test/detectcone:/opt
#         - ./detectcone:/opt
#         - "/dev/shm:/dev/shm"
#         #- ./model:/opt/model
#         - /home/cfsd/project/autonomous-system-usecases/train-model/model:/opt/model
#        depends_on:
#         - proxy-camera
#        ulimits:
#          memlock:
#            soft: 5600000 #1516032
#            hard: 5600000
#        command: "cfsd18-perception-detectcone --cid=${CID} --name=cam0 --width=2560 --height=720 --bpp=24 --threshold=0.6
#        --timeDiffMilliseconds=40 --separationTimeMs=20 --checkLidarMilliseconds=1000 --senderStamp=118 --attentionSenderStamp=116
#        --offline=0 --annotate=0 --stateMachineId=1401 --readyStateMachine=0 --forwardDetection=0 --fastThreshold=20 --orbPatchSize=31
#        --matchDistance=1.5"    

    proxy-velodyne16:
        image: chalmersrevere/opendlv-device-lidar-vlp16-multi:v0.0.7
        network_mode: "host"
        volumes:
            - .:/opt/opendlv.data
        working_dir: "/opt/opendlv.data"
        command: "opendlv-device-lidar-vlp16 --vlp16_ip=0.0.0.0 --vlp16_port=2368 --cid=${CID}"

    #proxy-ellipse2n
    #image need to be built locally
    opendlv-proxy-ellipse2n:
        image: proxy-imu:local
        network_mode: "host"
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        command: "opendlv-proxy-ellipse2n --cid=${CID} --id=112 --idRawData=108"
    
    cfsd18-sensation-attention:
        #latest
        image: chalmersfsd/cfsd18-sensation-attention:pre-release-69baa73
        #0714-test
        #image: chalmersfsd/cfsd18-sensation-attention:pre-release-faac13f
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=116 --xBoundary=3 --yBoundary=30 --zUpperBoundary=0.6
        --groundClusterDistanceThreshold=0.3 --groundClusterSizeThreshold=60 --connectDistanceThreshold=0.15 --minNumOfPointsForCone=2
        --maxNumOfPointsForCone=300 --coneRadiusThreshold=0.15 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1
        --inlierFoundThreshold=500 --numberOfIterations=30 --stateMachineId=1401 --readyStateMachine=0"


#    opendlv-logic-cfsd18-sensation-slam:
#        #latest  
#        image: chalmersfsd/opendlv-logic-cfsd18-sensation-slam:pre-release-689f21b
#        network_mode: "host"
#        depends_on:
#            - proxy-camera
#            - proxy-velodyne16
#            - opendlv-proxy-ellipse2n
#        ipc: host
#        command: "opendlv-logic-cfsd18-sensation-slam --cid=${CID} --id=120 --detectConeId=116 --estimationId=114
#             --gatheringTimeMs=20 --sameConeThreshold=1.5 --refLatitude=57.719264 --refLongitude=11.957777
#             --timeBetweenKeyframes=150 --coneMappingThreshold=4 --conesPerPacket=20 --lapSize=20 --localization=0 --stateMachineId=1401"


    ukf:
        #latest
        #image: chalmersfsd/cfsd18-perception-ukf:pre-release-8f682c3
        #update
        image: chalmersfsd/cfsd18-perception-ukf:pre-release-75cce1a
        network_mode: host
        ipc: host
        command: "opendlv-logic-cfsd18-sensation-ukf --cid=${CID} --cidDan=219 --id=114 --rackId=1206 --estimationId=112
        --estimationIdRaw=108 --stateMachineId=1401 --wheelEncoderIdLeft=1504 --wheelEncoderIdRight=1505 --refLatitude=57.719264 
        --refLongitude=11.957777 --Qx=1 --Qy=1 --QvelX=0.5 --QvelY=0.1 --Qyaw=0.2 --Qheading=1 --Rx=0.2 --Ry=0.2 --RvelX=0.3 
        --RaccX=0.00059 --RaccY=1 --Ryaw=0.2 --Rheading=0.1 --m=210 --Iz=105 --g=9.82 --l=1.53 --lf=0.765 --lr=0.765 --mu=0.9"


    cfsd18-cognition-detectconelane:
        image: chalmersfsd/cfsd18-cognition-detectconelane:pre-release-d69b5a4
        network_mode: "host"
        command: "/usr/bin/cfsd18-cognition-detectconelane --cid=${CID} --verbose=0 --id=211 --detectConeId=118 --slamId=120 --simDetectConeId=231 --attentionId=116 \
        --gatheringTimeMs=50 --separationTimeMs=10 \
        --alwaysSlam=${FAKESLAM} --guessDistance=3 --minGuessSeparation=1.5 --maxConeAngle=3 \
        --maxConeWidthSeparation=3.0 --widthSeparationMargin=1.0 \
        --maxConeLengthSeparation=5.0 --lengthSeparationMargin=1.0 \
        --nLapsToGo=1 --lapCounterLockTime=10 --refLatitude=57.719264 --refLongitude=11.957777 \
        --useAccelerationMode=1"


    cfsd18-cognition-acceleration:
        image: chalmersfsd/cfsd18-cognition-acceleration:pre-release-bcfb8c3
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/usr/bin/cfsd18-cognition-acceleration --cid=${CID} --verbose=0 --id=221 --surfaceId=211 --speedId=114 --slamId=120 \
        --gatheringTimeMs=50 --separationTimeMs=10 \
        --wheelAngleLimit=10 --wheelBase=${WB} --frontToCog=${FTC} \
        --useMoveOrigin=1 --steerRate=30 \
        --startAimVel=0.5 --useAyReading=0 --velocityLimit=30 --mu=${MU} --axLimitPositive=5 --axLimitNegative=-10 --headingErrorDependency=0.7f \
        --aKp=1 --aKd=0 --aKi=0 --bKp=2 --bKd=0.1 --bKi=0.05 --sKp=0.5 --sKd=0 --sKi=0.5 
        --trustInLastPathPoint=0.5 --aimDistance=50.0"

    steering:
        image: chalmersfsd/logic-action-steering:pre-release-06475ac
        network_mode: "host"
        command: "steering --cid=${CID} --cidSteering=219 --id=1 --verbose=1 --Kp=1"

    motion:
        image: chalmersfsd/logic-action-motion:pre-release-6432d58
        network_mode: "host"
        command: "motion --cid=${CID} --cidSM=219 --constantSpeed=1 --speedRequest=2 --id=1 --verbose=1"

#    brakes:
#        image: chalmersfsd/logic-action-brakes:pre-release-6a1431c
#        network_mode: "host"
#        command: "brakes --cid=${CID} --cidBraking=219 --id=1 --verbose=1"
