# This is a basic .yml file for CFSD19
# it includes ZED camera and ellipse2n interface, data recording microservices
version: '2'

services: 
    
    cfsd-cognition-acceleration:
        image: chalmersfsd/cfsd-action-longitudinal-control:test-piControl9
        network_mode: "host"
        command: "motion --cid=${CID} --freq=2"

    recorder:
       image: chrberger/cluon-amd64:latest
       network_mode: "host"
       volumes:
       - ./recordings${CID}cluon:/opt/recordings
       working_dir: "/opt/recordings"
       command: sh -c "cluon-OD4toStdout --cid=${CID} > `date +CID-${CID}-${missionname}-recording-%Y-%m-%d_%H%M%S.rec`"
   
    proxy-imu:
        image: chalmersfsd/cfsd-proxy-imu:v1.0.0
        network_mode: "host"
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        command: "opendlv-proxy-ellipse2n --cid=${CID} --id=112"