version: '2'

services: 
    stm32-lynx:
        image: chalmersfsd/opendlv-device-stm32-lynx:test-first-version2
        network_mode: "host"
        devices:
            - "${USBdevice}:${USBdevice}"
        command: "opendlv-device-stm32-lynx --cid=${CID} --cidGpio=${CID} --cidpwm=${CID} --freq=30 -id=1 --device=${USBdevice} --verbose"
#--rackPos --steerPos --ebsLine --ebsAct --servTank --pressReg --asms --clamped --ebsOK

    #can-service
    cangw-lynx:
        image: chalmersfsd/cfsd-proxy-cangw-lynx:test11
        network_mode: "host"
        command: "cfsd-proxy-cangw-lynx --cid=${CID} --can=can0"

    cangw-res:
        image: chalmersfsd/cfsd-proxy-cangw-res:test9
        network_mode: "host"
        command: "opendlv-device-cangw-lynx --cid=${CID} --can=can1"

    state-machine:
        image: chalmersfsd/cfsd-logic-lynx-state-machine:test-extended-message-set9
        network_mode: "host"
        depends_on:
         - cangw-res
        command: "state-machine --cid=${CID} --cidAnalog=${CID} --cidGpio=${CID} --cidPwm=${CID} --freq=2.0f"
    
    cfsd-mission-control:
        image: chalmersfsd/cfsd-logic-lynx-mission-control:test-inspection6
        network_mode: "host"
        command: " --cid=131 --frequency=60 --verbose"