version: '2'

services:
    technical-inspection:
      image: chalmersfsd/logic-technical-inspection:pre-release-12c5061
      network_mode: "host"
      command: "techInspec --cid=${CID} --cidBB=${cidBB}"

    recorder48:
        image: chrberger/cluon-amd64:latest
        restart: on-failure
        network_mode: "host"
        volumes:
        - ./recordings48cluon:/opt/recordings
        working_dir: "/opt/recordings"
        command: sh -c "cluon-OD4toStdout --cid=${CID} > `date +CID-48-recording-%Y-%m-%d_%H%M%S.rec`"

    recorder219:
        image: chrberger/cluon-amd64:latest
        restart: on-failure
        network_mode: "host"
        volumes:
        - ./recordings219cluon:/opt/recordings
        working_dir: "/opt/recordings"
        command: sh -c "cluon-OD4toStdout --cid=${cidBB} > `date +CID-219-recording-%Y-%m-%d_%H%M%S.rec`"

    cfsd18-sim-visualization:
        image: chalmersfsd/cfsd18-sim-visualization:pre-release-778bfb6
        network_mode: "host"
        command: "--cid=219"

