version: '2'

services:
    # recorder 
    recorder219:
       image: chrberger/cluon-amd64:latest
       restart: on-failure
       network_mode: "host"
       volumes: 
       # - ./recordings219cluon:/opt/recordings
       - /media/usb-test/cfsd-test/recordings219cluon:/opt/recordings
       working_dir: "/opt/recordings"
       command: sh -c "cluon-OD4toStdout --cid=219 > `date +CID-219-recording-%Y-%m-%d_%H%M%S.rec`"  

    recorder48:
       image: chrberger/cluon-amd64:latest
       restart: on-failure
       network_mode: "host"
       volumes:
       #- ./recordings48cluon:/opt/recordings
       - /media/usb-test/cfsd-test/recordings48cluon:/opt/recordings
       working_dir: "/opt/recordings"
       command: sh -c "cluon-OD4toStdout --cid=48 > `date +CID-48-recording-%Y-%m-%d_%H%M%S.rec`"

    proxy-camera:
       #image: proxy-camera:local
       #local image, change ENTRYPOINT to CMD in Dockerfile to enable change nice value from command line
       image: proxy-camera:0af4299
       network_mode: host
       group_add:
           - video
       ipc: host
       privileged: true
       user: root
       devices:
           - "/dev/video0:/dev/video0"
       environment:
           - DISPLAY=$DISPLAY
       #    - CLUON_SHAREDMEMORY_POSIX=1
       volumes:
           - /tmp/.X11-unix:/tmp/.X11-unix
           - "/dev/shm:/dev/shm"
       ulimits:
         memlock:
           soft: 5600000 #1516032
           hard: 5600000
       command: "nice -n -10 opendlv-device-camera-opencv --name=cam0 --bgr2rgb --cid=${CID} --camera=/dev/video0 --width=2560 --height=720 --bpp=24 --freq=15"


    cfsd18-perception-detectcone:
        image: "chalmersfsd/cfsd18-perception-detectcone:pre-release-c0c3341"
        network_mode: "host"
        ipc: host
        working_dir: /opt
        environment:
          - DISPLAY=$DISPLAY
        volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /media/usb-test/cfsd-test/detectcone:/opt
         - "/dev/shm:/dev/shm"
         - ./model:/opt/model
        depends_on:
         - proxy-camera
        ulimits:
          memlock:
            soft: 5600000 #1516032
            hard: 5600000
        command: "cfsd18-perception-detectcone --cid=${CID} --name=cam0 --width=2560 --height=720 --bpp=24 --threshold=0.6
        --timeDiffMilliseconds=40 --separationTimeMs=20 --checkLidarMilliseconds=1000 --senderStamp=118 --attentionSenderStamp=116
        --offline=0 --annotate=0 --stateMachineId=1401 --readyStateMachine=0 --forwardDetection=0 --fastThreshold=20 --orbPatchSize=31
        --matchDistance=1.5"    

    proxy-velodyne16:
        image: chalmersrevere/opendlv-device-lidar-vlp16-multi:v0.0.7
        network_mode: "host"
        volumes:
            - .:/opt/opendlv.data
        working_dir: "/opt/opendlv.data"
        command: "opendlv-device-lidar-vlp16 --vlp16_ip=0.0.0.0 --vlp16_port=2368 --cid=${CID}"

    #proxy-ellipse2n
    #image need to be built locally
    opendlv-proxy-ellipse2n:
        image: proxy-imu:local
        network_mode: "host"
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        command: "opendlv-proxy-ellipse2n --cid=${CID} --id=112 --idRawData=108"
    
    cfsd18-sensation-attention:
        image: chalmersfsd/cfsd18-sensation-attention:pre-release-faac13f
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=116 --xBoundary=4 --yBoundary=12 --groundLayerZ=-0.3 --coneHeight=0.5 --connectDistanceThreshold=0.3 --layerRangeThreshold=0.06 --minNumOfPointsForCone=10 --maxNumOfPointsForCone=300 --farConeRadiusThreshold=0.17 --nearConeRadiusThreshold=0.13 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1 --inlierFoundThreshold=150 --numberOfIterations=10 --stateMachineId=1401"

    cfsd18-perception-ukf:
        image: chalmersfsd/cfsd18-perception-ukf:pre-release-4a36710
        network_mode: "host"
        command: "opendlv-logic-cfsd18-sensation-ukf --cid=${CID} --cidDan=219 --id=114 --rackId=1206 --estimationId=112 --estimationIdRaw=108 --stateMachineId=1401 --wheelEncoderIdLeft=1504 --wheelEncoderIdRight=1505 --refLatitude=57.710487 --refLongitude=11.950660 --Qx=1 --Qy=1 --QvelX=0.5 --QvelY=0.2 --Qyaw=0.2 --Qheading=1 --Rx=0.2 --Ry=0.2 --RvelX=0.3 --RaccX=0.00059 --RaccY=0.01 --Ryaw=0.03 --Rheading=0.05 --m=210 --Iz=105 --g=9.82 --l=1.53 --lf=0.765 --lr=0.765 --mu=0.9"

