# This is a basic .yml file for CFSD19
# it includes ZED camera and ellipse2n interface, data recording microservices
version: '2'

services: 
    recorder:
       image: chrberger/cluon-amd64:latest
       network_mode: "host"
       volumes:
       - ./recordings${CID}cluon:/opt/recordings
       working_dir: "/opt/recordings"
       command: sh -c "cluon-OD4toStdout --cid=${CID} > `date +CID-${CID}-${missionname}-recording-%Y-%m-%d_%H%M%S.rec`"
