# This is a basic .yml file for CFSD19
# it includes ZED camera, ellipse2n interface, data recording microservices
version: '2'

services: 

    video-h264-encoder-amd64:
        #build:
            #context: https://github.com/chalmers-revere/opendlv-video-h264-encoder.git
            #dockerfile: Dockerfile.amd64
        image: video-h264-encoder-amd64:latest
        restart: on-failure
        network_mode: "host"
        ipc: "host"
        depends_on: 
        - proxy-camera
        volumes:
        - /tmp:/tmp
        command: "--cid=${CID} --name=video0.i420 --width=${width} --height=${height}"

    proxy-camera:
       image: chalmersrevere/opendlv-device-camera-v4l-multi:v0.0.8
       network_mode: host
       group_add:
           - video
       ipc: host
       user: root
       devices:
           - "/dev/video0:/dev/video0"
       environment:
           - DISPLAY=$DISPLAY
       volumes:
           - /tmp/.X11-unix:/tmp/.X11-unix
           - /tmp:/tmp
       command: "--camera=/dev/video0 --width=${width} --height=${height} --freq=${freq}"

    proxy-imu:
        image: chalmersfsd/cfsd-proxy-imu:v1.0.0
        network_mode: "host"
        devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
        command: "opendlv-proxy-ellipse2n --cid=${CID} --id=112"
